### ISSUE TITLE
Model specifications and changes

### ISSUE THREAD

**Issue by kssvrk** [kssvrk/YorAppBackend#3]
After the first version of models were done, I see that there might be optimizations that should me made.

- Firstly the attributes which have fixed choices like gender, role , enable status should not be charfield. Please refer this to implment it. https://stackoverflow.com/questions/8077840/choicefield-in-django-model
-  URL fields like profile image should have more length. Increase such lengths to 150. Or just use text field.
- Modify array fields as arrays https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#arrayfield
- Refer by use ID
-Open time double aayi and Store admin double aayi. We have to take care.

**Comment by Xdev200** [comment]
Updated Fixed Choices
Currently, we are using SQLite, Array is not supported
Removed Duplicated Fields
